import: DemoCallback.py


logging:
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: AutomationOne
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: AutomationOnePlusTime
      level: DEBUG
      filename: AutomationOne.log
      maxBytes: 1000000
      backupCount: 1

interfaces:
  - name: &mqtt MQTT Interface
    type: MQTT
    clientID: A1GW-SDK1-005
    host: test.mosquitto.org
    port: 1883
    topicSub: /AutomationOne/A1GW-SDK1-005/cmd
    topicPub: /AutomationOne/A1GW-SDK1-005/Values
    parser: jsonParser
    encoder: jsonEncoder

  - name: &mod Modbus Interface
    type: Modbus
    port: /dev/ttymxc0
    method: rtu
    baudrate: 38400
    parity: E


  

nodes:
  - name: Drehgeber [MQTT]
    type: MQTT
    interface: *mqtt
    accessType: write
    mqttID: Harmonischer Oszillator

  - name: Sollwert
    type: MQTT
    interface: *mqtt
    accessType: read
    mqttID: Sollwert
    onChange: logValue

  - name: Drehgeber
    type: Modbus
    interface: *mod
    unit: 11
    address: 0
    functionCode: 4
    dataType: uint16
    pollRate: 2
    sensitivity: 10
    onChange: logValue

  - name: Klappe
    type: Modbus
    interface: *mod
    unit: 12
    address: 0
    functionCode: 16
    dataType: int16
    onChange: logValue

connections:
  - name: Signalstärke [Connection]
    inNode: Drehgeber
    outNode: Drehgeber [MQTT]

  - name: Drehgeber Klappe
    inNode: Drehgeber
    outNode: Klappe    

  - name: Sollwert Klappe
    inNode: Sollwert
    outNode: Klappe
